const $=id=>document.getElementById(id);let token='',protocol=null,results=null,selectedSample=null;
async function api(path,data){const res=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Token':token},body:JSON.stringify(data)}:{});const x=await res.json();if(x.error)throw Error(x.error);return x;}
const labels={coherence:'连贯性',consistency:'事实一致性',fluency:'表达流畅性',relevance:'任务相关性'};
function view(id){['work','results','method'].forEach(n=>$(n).classList.toggle('hidden',id!==n));['work','result','method'].forEach(n=>$(n+'-tab').classList.toggle('active',(n==='result'?'results':n)===id));}
$('work-tab').onclick=()=>view('work');$('result-tab').onclick=()=>view('results');$('method-tab').onclick=()=>view('method');
function condition(){return protocol.conditions[$('condition').value]}
function loadPrompt(){$('live-prompt').value=condition().prompt;$('live-output').value='';$('sample-scores').textContent='载入实验样本后显示。';$('response-meta').textContent='';selectedSample=null;}
function loadSample(){if(!results){$('status').textContent='尚无已完成记录。';return}const s=results.samples.find(s=>s.condition===condition().id&&s.replicate===+$('replicate').value+1);if(!s)return;selectedSample=s;$('live-output').value=s.text;$('response-meta').textContent='样本 '+s.sample_id+' · '+s.generation.model+' · API ID '+s.generation.id;$('sample-scores').innerHTML=Object.entries(labels).map(([d,label])=>`<p style="margin:14px 0">${label}<br><strong style="font-size:26px;color:#0067c0">${s.summary.dimensions[d]?.mean.toFixed(2)??'缺失'}</strong> / 5</p>`).join('')+`<p class="hint">有效 ${s.summary.valid_n}/20 次；无效 ${s.summary.invalid_n} 次。</p>`;}
$('load-result').onclick=loadSample;$('replicate').onchange=loadSample;
function renderResults(){if(!results)return;$('results-table').innerHTML='<table><thead><tr><th>条件</th>'+Object.values(labels).map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+results.conditions.map(c=>'<tr><th>'+c.id+'</th>'+Object.keys(labels).map(d=>{const v=c.dimensions[d];return '<td>'+v.mean.toFixed(2)+' ± '+v.sd_between_texts.toFixed(2)+'</td>'}).join('')+'</tr>').join('')+'</tbody></table>';$('chart').innerHTML='<h2 style="margin-top:24px">主指标：连贯性（1—5 分）</h2>'+results.conditions.map(c=>`<div style="display:flex;align-items:center;gap:12px;margin:12px 0"><span style="width:75px">${c.id}</span><div style="width:75%;background:#edf1f5"><div style="width:${c.dimensions.coherence.mean/5*100}%;height:22px;background:#0067c0"></div></div><strong>${c.dimensions.coherence.mean.toFixed(2)}</strong></div>`).join('');}
$('generate').onclick=async()=>{$('generate').disabled=true;$('sample-scores').textContent='新生成文本尚未纳入重复评判。';$('status').textContent='正在调用 DeepSeek…';try{const x=await api('/api/generate',{prompt:$('live-prompt').value});$('live-output').value=x.text;$('response-meta').textContent=x.model+' · '+x.id+' · '+x.finish_reason;$('status').textContent='真实生成完成。此文本未自动评分。';}catch(e){$('status').textContent=e.message}finally{$('generate').disabled=false}};
$('experiment').onclick=async()=>{try{await api('/api/experiment',{});results=null;$('status').textContent='完整实验已启动。'}catch(e){$('status').textContent=e.message}};
$('download').onclick=()=>{if(!results)return;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(results,null,2)],{type:'application/json'}));a.href=url;a.download='deepseek-experiment-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
async function poll(){try{const s=await api('/api/status');$('experiment').disabled=['planning','generating','judging'].includes(s.status);$('status').textContent={idle:'后端已连接，可生成或运行完整实验。',planning:'准备固定评价步骤',generating:'正在真实生成文本',judging:'正在匿名重复评判',complete:'实验完成，全部记录已保存',failed:'实验失败：'+s.error}[s.status]+(s.total?' · '+s.done+'/'+s.total:'');if(s.status==='complete'&&!results){results=await api('/api/results');renderResults();loadSample();}}catch(e){$('status').textContent='本地后端未连接，请启动 server.py。'}}
(async()=>{protocol=await(await fetch('protocol.json')).json();$('condition').innerHTML=protocol.conditions.map((c,i)=>`<option value="${i}">${c.id}</option>`).join('');$('condition').onchange=()=>{loadPrompt();if(results)loadSample()};loadPrompt();$('rubric').innerHTML=Object.values(protocol.rubric).map(d=>'<h2>'+d.name+'</h2><p>'+d.criterion+'</p><ol>'+d.anchors.map(a=>'<li>'+a+'</li>').join('')+'</ol>').join('');try{const s=await api('/api/session');token=s.token;$('connection').textContent=s.model+' / '+s.judge;try{results=await api('/api/results');renderResults();loadSample()}catch{}await poll();setInterval(poll,5000)}catch{$('connection').textContent='请运行本地后端';$('status').textContent='直接双击仅能查看页面；API 功能需要 python server.py。'}})();

