const DATA={"checks": [{"name": "主题", "criterion": "明确讨论联邦学习"}, {"name": "本地数据", "criterion": "明确原始数据留在参与方本地"}, {"name": "训练与聚合", "criterion": "同时说明本地训练与模型更新聚合"}, {"name": "具体场景", "criterion": "至少一个具体应用场景，如移动终端"}, {"name": "明确挑战", "criterion": "指出具体挑战，如数据异质性或通信成本"}, {"name": "结构顺序", "criterion": "背景、问题、本文工作三部分完整且依次出现"}, {"name": "工作范围", "criterion": "明确本文梳理什么机制或讨论什么问题"}, {"name": "学术表达", "criterion": "无“很火、大家都知道”等口语或空泛宣传句"}, {"name": "引用支持", "criterion": "正文引用确实支持紧邻事实，须人工查原文"}, {"name": "书目对应", "criterion": "作者、题名、年份、载体可检索，并与编号对应"}], "samples": [{"name": "第1轮", "text": "联邦学习现在很火，大家都在研究。它可以让数据留在本地，不用集中到一个地方。这种技术很有意义，也有很大的发展前景。本文将介绍联邦学习，希望让大家更好地了解它。", "reference": "", "passed": [1, 1, 0, 0, 0, 0, 0, 0, 0, 0], "evidence": ["“联邦学习”", "“数据留在本地”", "", "", "", "", "", "", "", ""], "prompt": "帮我写一段关于联邦学习的论文引言。"}, {"name": "第2轮", "text": "联邦学习是一类分布式机器学习方法，允许多个参与方在保留本地数据的条件下开展协作建模。各参与方使用本地数据训练模型，并通过聚合模型更新形成共享模型。该方法为分散数据的联合利用提供了一种技术路径，其核心在于协调本地计算与全局模型更新。本文介绍联邦学习。", "reference": "", "passed": [1, 1, 1, 0, 0, 0, 0, 1, 0, 0], "evidence": ["“联邦学习”", "“保留本地数据”", "“本地数据训练模型”“聚合模型更新”", "", "", "", "", "书面语言，无列举的口语或宣传句", "", ""], "prompt": "你是一名学术写作助教。请写一段关于联邦学习的综述式论文引言，约 150 字，使用书面语言。"}, {"name": "第3轮", "text": "移动终端持续产生分散数据，集中汇集这些数据受到数据治理与传输成本的约束。联邦学习使参与方保留本地数据，通过本地训练与模型更新聚合实现协作建模，为移动终端上的联合学习提供了方法。然而，参与方数据分布的差异与通信开销增加了训练难度。本文围绕联邦学习的基本流程，梳理本地训练和服务器聚合机制，并讨论数据异质性与通信成本对方法应用的影响。", "reference": "", "passed": [1, 1, 1, 1, 1, 1, 1, 1, 0, 0], "evidence": ["“联邦学习”", "“保留本地数据”", "“本地训练与模型更新聚合”", "“移动终端”", "“数据分布的差异与通信开销”", "背景：移动终端；问题：然而；工作：本文围绕", "“梳理本地训练和服务器聚合机制”", "客观描述机制和挑战", "", ""], "prompt": "你是一名学术写作助教。请写一段关于联邦学习的综述式论文引言，约 150—200 字。按背景、问题、本文工作组织，使用客观学术语言。本文工作限定为原理梳理与挑战讨论，不得虚构实验或新算法。"}, {"name": "第4轮", "text": "移动终端产生的分散数据为机器学习提供了应用基础，但集中收集数据面临数据治理与传输成本约束。联邦学习允许参与方保留本地数据，通过本地训练与模型更新聚合协作训练共享模型[1]。在移动终端场景中，数据分布差异与通信开销仍是需要考虑的问题[1]。本文梳理本地训练及服务器聚合流程，并讨论数据异质性和通信成本对应用的影响。该机制不等同于完整隐私保障，具体风险仍需另行评估。", "reference": "[1] McMahan, B., et al. (2017). Communication-Efficient Learning of Deep Networks from Decentralized Data. AISTATS, PMLR 54, 1273–1282. https://proceedings.mlr.press/v54/mcmahan17a.html", "passed": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], "evidence": ["“联邦学习”", "“保留本地数据”", "“本地训练与模型更新聚合”", "“移动终端场景”", "“数据分布差异与通信开销”", "背景：分散数据；问题：差异与开销；工作：本文梳理", "“梳理本地训练及服务器聚合流程”", "没有口语化宣传句", "已按 McMahan 等（2017）摘要及正文核对机制与通信/数据差异描述", "已核验 PMLR 54:1273–1282 与正文 [1] 对应"], "prompt": "你是一名学术写作助教。请写一段约 150—200 字的联邦学习综述式引言，依次写背景、问题和本文工作。必须包含本地数据、本地训练、模型聚合、移动终端场景、数据异质性和通信成本。仅使用给定文献[1]，在受其支持的事实后标注[1]，文后按作者、题名、会议、年份、页码列出参考文献。使用客观语言，不虚构成果，不将数据留在本地等同于完整隐私保障。给定文献：McMahan et al., Communication-Efficient Learning of Deep Networks from Decentralized Data, AISTATS, 2017, 1273–1282。"}]};
const $=id=>document.getElementById(id);
let current=0;
const drafts=DATA.samples.map(s=>({prompt:s.prompt,text:s.text,flags:[...s.passed],custom:false,result:null}));
function reset(message){drafts[current].result=null;window.result=null;$('score').innerHTML='— <small>/ 100</small>';$('score-caption').textContent='待运行 · 每项 10 分';$('status').textContent=message;}
function counts(){$('prompt-count').textContent=$('prompt').value.length+' 字符';$('text-count').textContent=$('text').value.length+' 字符';}
function renderChecks(){const d=drafts[current];$('checks').innerHTML=DATA.checks.map((c,j)=>`<label><input type="checkbox" data-item="${j}" ${d.flags[j]?'checked':''}><span>${c.name}</span><em>10</em></label>`).join('');$('checks').querySelectorAll('input').forEach(el=>el.onchange=()=>{d.flags[+el.dataset.item]=+el.checked;reset('核对记录已修改，请点击“运行核对汇总”。')});$('evidence').replaceChildren();DATA.checks.forEach((c,j)=>{const li=document.createElement('li');li.textContent=c.name+'：'+c.criterion+'。 '+(d.custom?'自定义文本，请根据原句重新核验。':(DATA.samples[current].evidence[j]||'样例中未找到足够证据。'));$('evidence').append(li)});}
function select(i){current=i;const d=drafts[i];$('prompt').value=d.prompt;$('text').value=d.text;$('reference').textContent=d.custom?'':DATA.samples[i].reference;$('version').textContent='当前：第 '+(i+1)+' 轮';document.querySelectorAll('#nav button').forEach((b,j)=>{b.classList.toggle('active',j===i);b.setAttribute('aria-pressed',String(j===i))});renderChecks();counts();reset(d.custom?'已载入编辑草稿，请人工复核后运行。':'已载入第 '+(i+1)+' 轮教学样例和人工核对记录。');}
$('nav').innerHTML=DATA.samples.map((s,i)=>`<button type="button">第 ${i+1} 轮</button>`).join('');$('nav').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>select(i));
$('prompt').oninput=()=>{drafts[current].prompt=$('prompt').value;counts();reset('提示词已修改；待评文本不会自动生成，请粘贴对应输出。')};
$('text').oninput=()=>{const d=drafts[current];d.text=$('text').value;d.custom=true;d.flags=Array(10).fill(0);$('reference').textContent='';renderChecks();counts();reset('文本已修改，旧评分与勾选已清空。请重新逐项核验。')};
$('run').onclick=()=>{const d=drafts[current];if(!d.text.trim()){reset('请先输入待评文本。');return}const score=DemoCore.checklistScore(d.flags);$('score').innerHTML=score+' <small>/ 100</small>';$('score-caption').textContent=d.flags.filter(Boolean).length+' 项通过 × 10 分';$('status').textContent='汇总完成；这是人工核对结果，不是模型自动语义评分。';window.result=d.result={round:current+1,score,checks:[...d.flags],prompt:d.prompt,text:d.text,mode:d.custom?'custom_human_checklist':'teaching_sample_human_checklist'};};
$('restore').onclick=()=>{const s=DATA.samples[current];drafts[current]={prompt:s.prompt,text:s.text,flags:[...s.passed],custom:false,result:null};select(current)};
$('export').onclick=()=>{const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify({round:current+1,...drafts[current]},null,2)],{type:'application/json'}));a.href=url;a.download='round-'+(current+1)+'-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='当前文本与核对记录已导出为 JSON。';};select(0);
